plugins {
	id "com.crystaelix.loom" version "1.10.0"
	id "eclipse"
	id "idea"
	id "maven-publish"
	id "net.kyori.blossom" version "[1,2)"
	id "me.modmuss50.mod-publish-plugin" version "0.8.4"
}

repositories {
	mavenCentral()
	flatDir {
		dirs "libs"
	}
	exclusiveContent {
		forRepository {
			maven {
				url = "https://maven.blamejared.com/"
			}
		}
		filter {
			includeGroup "mezz.jei"
			includeGroup "vazkii.patchouli"
			includeGroup "CraftTweaker2"
		}
	}
	exclusiveContent {
		forRepository {
			maven {
				url = "https://maven.covers1624.net/"
			}
		}
		filter {
			includeGroup "codechicken"
		}
	}
	exclusiveContent {
		forRepository {
			maven {
				url = "https://dvs1.progwml6.com/files/maven/"
			}
		}
		filter {
			includeGroup "slimeknights.mantle"
			includeGroup "slimeknights"
		}
	}
	exclusiveContent {
		forRepository {
			maven {
				url = "https://maven.amadornes.com/"
			}
		}
		filter {
			includeGroup "MCMultiPart2"
		}
	}
	exclusiveContent {
		forRepository {
			maven {
				//url = "https://maven.tterrag.com/"
				url = "https://modmaven.dev/"
			}
		}
		filter {
			includeGroup "mcjty.theoneprobe"
			includeGroup "team.chisel.ctm"
		}
	}
	exclusiveContent {
		forRepository {
			maven {
				url = "https://repo.cleanroommc.com/releases/"
				metadataSources {
					mavenPom()
					ignoreGradleMetadataRedirection()
				}
			}
		}
		filter {
			includeGroup "com.cleanroommc"
			includeGroup "zone.rong"
		}
	}
	exclusiveContent {
		forRepository {
			maven {
				url = "https://cursemaven.com/"
			}
		}
		filter {
			includeGroup "curse.maven"
		}
	}
}

def mcVersion = "1.12.2"
def modName = "Radiessency"
def modId = "radiessency"
def specVersion = "1"
def vendor = "thelm"

group = "thelm.radiessency"
version = "1.0.0.0"

archivesBaseName = "${modName}-${mcVersion}"

sourceSets {
	main {
		output.resourcesDir = java.destinationDirectory = layout.buildDirectory.dir("outputs/main")
	}
}

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(8)
		vendor = JvmVendorSpec.AZUL
	}
	withSourcesJar()
}

tasks.withType(JavaCompile).configureEach {
	options.encoding = "UTF-8"
}

loom {
	silentMojangMappingsLicense()
	runs {
		configureEach {
			property "fabric.log.console.level", "debug"
			environmentVariable "MC_VERSION", mcVersion
		}
		client {
			programArg "--username=Dev"
		}
		server
	}
	generatedIntermediateMappings()
}

dependencies {
	// Log4j
	implementation "org.apache.logging.log4j:log4j-core:2.24.3"

	// Minecraft
	minecraft "com.mojang:minecraft:1.12.2"
	mappings "de.oceanlabs.mcp:mcp_stable:39-1.12"
	legacyForge "net.minecraftforge:forge:1.12.2-14.23.5.2860"

	// Dependencies
	modImplementation "curse.maven:baubles-227083:2518667"
	modImplementation "vazkii.patchouli:Patchouli:1.0-23.6"
	modImplementation "codechicken:CodeChickenLib:1.12.2-3.2.3.358:universal"
	modImplementation "mezz.jei:jei_1.12.2:4.16.1.1013"
    modImplementation "team.chisel.ctm:CTM:MC1.12.2-1.0.2.31"
	modImplementation "curse.maven:hwyla-253449:2568751"
	modImplementation "mcjty.theoneprobe:TheOneProbe-1.12:1.12-1.4.28-17"

	modImplementation("CraftTweaker2:ZenScript:4.1.20.704") {transitive = false}
	modImplementation("CraftTweaker2:CraftTweaker2-API:4.1.20.704") {transitive = false}
	modImplementation("CraftTweaker2:CraftTweaker2-MC1120-Main:1.12-4.1.20.704") {transitive = false}
	implementation("zone.rong:mixinbooter:10.6") {transitive = false}
	modImplementation("com.cleanroommc:groovyscript:1.2.4") {transitive = false}

	modImplementation "curse.maven:guide-api-228832:2645992"
	modImplementation "curse.maven:blood-magic-224791:2822288"

	modImplementation "curse.maven:thaumcraft-223628:2629023"
	modImplementation "curse.maven:thaumic-jei-285492:2705304"

	// Testing
	modImplementation "curse.maven:mcmultipart-239431:2615930"
	modImplementation "curse.maven:mekanism-268560:2835175"

	// Performance
	modImplementation "curse.maven:reid-629017:6292779"
	modImplementation "curse.maven:vintagefix-871198:6609247"
	modImplementation "curse.maven:lolasm-460609:6333774"
}

def replacements = [
	"0@VERSION@": version
]

blossom {
	replaceToken(replacements)
}

processResources {
	inputs.properties(replacements)
	filesMatching(["mcmod.info", "META-INF/mods.toml", "META-INF/neoforge.mods.toml", "fabric.mod.json"]) {
		filter {
			it.replace(replacements)
		}
	}
}

def manifestAttributes = [
	"Specification-Title": modName,
	"Specification-Vendor": vendor,
	"Specification-Version": specVersion,
	"Implementation-Title": archivesBaseName,
	"Implementation-Version": version,
	"Implementation-Vendor": vendor
]

jar {
	manifest.attributes(manifestAttributes)
}

sourcesJar {
	manifest.attributes(manifestAttributes)
}

publishing {
	publications {
		register("mavenJava", MavenPublication) {
			artifactId = archivesBaseName
			artifact remapJar
			artifact sourcesJar
		}
	}
	repositories {
		if(project.hasProperty("CrystaelixMavenUsername") && project.hasProperty("CrystaelixMavenPassword")) {
			maven {
				name = "CrystaelixMaven"
				url = "https://maven.crystaelix.com/releases/"
				credentials(PasswordCredentials)
			}
		}
	}
}

publishMods {
	file = remapJar.archiveFile
	version = displayName = "${mcVersion}-${project.version}"
	changelog = file("changelog.md").text
	type = ALPHA
	modLoaders.add("forge")
	additionalFiles.from(sourcesJar.archiveFile)

	//curseforge {
	//	accessToken = providers.gradleProperty("curseforge.token")
	//	projectId = ""
	//	minecraftVersions.add(mcVersion)
	//	requires "baubles"
	//	optional "ctm"
	//}

	//modrinth {
	//	accessToken = providers.gradleProperty("modrinth.token")
	//	projectId = ""
	//	minecraftVersions.add(mcVersion)
	//  optional "ctm"
	//}
}
